version: "3"

services:
  php:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    container_name: container-php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    links:
      - db
  db:           
    image: mysql:latest
    container_name: container-mysql-php
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root